### ISSUE TITLE
RPC system

### ISSUE THREAD

**Issue by jsannemo** [sjchat/sjchat#2]
For cross-system communication, we need a system for RPC:s.

Current suggestion is http://www.grpc.io/docs/, since it integrates well with bazel and has stable official implementations for the languages we will use.

https://github.com/grpc-ecosystem/grpc-gateway can be used to create the public-facing API servers.

**Comment by s4wny** [comment]
GRPC is in use now (https://github.com/sjchat/sjchat/blob/master/restapi/pom.xml#L106, https://github.com/sjchat/sjchat/tree/master/proto).
