### ISSUE TITLE
Set Access-Control-Allow-Origin in RestAPI

### ISSUE THREAD

**Issue by s4wny** [sjchat/sjchat#25]
Currently Access-Control-Allow-Origin isn't set in RestAPI and therefore we can't make AJAX request from the webserver to the RestAPI.

Error message from chrome:
`XMLHttpRequest cannot load http://localhost:8080/chat. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8082' is therefore not allowed access.`

Code:
```
$.get("http://localhost:8080/chat", function(data) {
	console.log(data);
});
```

**Comment by s4wny** [comment]
Probably related to #28 if we don't want to allow everyone to use our API.

**Comment by alanihre** [comment]
Commit aed5391 on backend-rest-api should solve this problem.

**Comment by s4wny** [comment]
@sjchat/frontend This is now live on production and staging.
