### ISSUE TITLE
Make the RestAPI work again

### ISSUE THREAD

**Issue by s4wny** [sjchat/sjchat#60]
The following RestAPI endpoints doesn't work anymore:

```
/chat
/chat/1/
/chat/1/messages
```
(see http://sjchat.wallstrom.it:8082/client.html or try it locally with `build.sh && run.sh`).

Related to #50 .

**Comment by jvikstrom** [comment]
It's /chat/1/message instead of /chat/1/messages. 

This is fixed in pr: #68

**Comment by s4wny** [comment]
Live on staging and is working: http://staging.sjchat.wallstrom.it:8082/client.html
